update docker puppet module

diff --git a/vamp/vagrant/modules/docker/templates/etc/init.d/docker-run.erb b/vamp/vagrant/modules/docker/templates/etc/init.d/docker-run.erb
--- a/vamp/vagrant/modules/docker/templates/etc/init.d/docker-run.erb
+++ b/vamp/vagrant/modules/docker/templates/etc/init.d/docker-run.erb
@@ -11,90 +11,72 @@
 # description: Docker container for <%= @title %>
 
 ### BEGIN INIT INFO
-## Provides:       docker-<%= @title %>
-## Required-Start: $network docker
-## Required-Stop: $network docker
-## Should-Start:
-## Should-Stop:
-## Default-Start: 2 3 4 5
-## Default-Stop:  0 1 6
-## Short-Description: start and stop docker container for <%= @title %>
-## Description: Docker container for <%= @title %>
-#### END INIT INFO
+# Provides:       <%= @service_prefix %><%= @sanitised_title %>
+# Required-Start: $network docker<% if @depends %><% @sanitised_depends_array.each do |d| %><%= " #{@service_prefix}#{d}" %><% end %><% end %>
+# Required-Stop: $network docker<% if @depends %><% @sanitised_depends_array.each do |d| %><%= " #{@service_prefix}#{d}" %><% end %><% end %>
+# Should-Start:
+# Should-Stop:
+# Default-Start: 2 3 4 5
+# Default-Stop:  0 1 6
+# Short-Description: start and stop docker container for <%= @title %>
+# Description: Docker container for <%= @title %>
+### END INIT INFO
 
-. /etc/init.d/functions
+if [ -e /etc/init.d/functions ]; then
+    . /etc/init.d/functions
+elif [ -e /lib/lsb/init-functions ]; then
+    . /lib/lsb/init-functions
+    failure() {
+        log_failure_msg "$@"
+        return 1
+    }
+    success() {
+        log_success_msg "$@"
+        return 0
+    }
+else
+    failure() {
+        echo "fail: $@" >&2
+        exit 1
+    }
+    success() {
+        echo "success: $@" >&2
+        exit 0
+    }
+fi
 
-docker="/usr/bin/<%= docker_command %>"
-prog="docker-<%= @sanitised_title %>"
-cidfile="/var/run/$prog.cid"
-lockfile="/var/lock/subsys/$prog"
+export HOME=/root/
+docker="/usr/bin/<%= @docker_command %>"
+prog="<%= @service_prefix %><%= @sanitised_title %>"
+if [ -d /var/lock/subsys ]; then
+    lockfile="/var/lock/subsys/$prog"
+else
+    unset lockfile
+fi
 
 start() {
     [ -x $docker ] || exit 5
 
-    if [ -f $cidfile ]; then
-        cid="$(cat $cidfile)"
-        if [ -n "$cid" ]; then
-            $docker ps --no-trunc=true|grep $cid
-            retval=$?
-            if [ $retval -eq 0 ]; then
-                failure
-                echo
-                printf "Container $cid is still running.\n"
-                exit 7
-            else
-                rm -f $lockfile $cidfile
-            fi
-        fi
+    if [ "true" = "$($docker inspect --format='{{.State.Running}}' <%= @sanitised_title %>)" ]; then
+       failure
+       printf "Container <%= @sanitised_title %> is still running.\n"
+       exit 7
     fi
 
     printf "Starting $prog:\t"
-    $docker run --cidfile=$cidfile -d=true \
-        <% if @username %>-u '<%= @username %>' <% end %> \
-        <% if @hostname %>-h '<%= @hostname %>'<% end %> \
-        <% if @disable_network %>-n false<% end %> \
-        <% if @privileged %>--privileged<% end %> \
-        <% if @detach %>--detach=true<% end %> \
-        <% if @dns %><% @dns_array.each do |address| %> \
-            --dns <%= address %><% end %> \
-        <% end %> \
-        <% if @dns_search %><% @dns_search_array.each do |domain| %> \
-            --dns-search <%= domain %><% end %> \
-        <% end %> \
-        <% if @env %><% @env_array.each do |env| %> \
-            -e <%= env %><% end %> \
-        <% end %> \
-        <% if @ports %><% @ports_array.each do |port| %> \
-            -p <%= port %><% end %> \
-        <% end %> \
-        <% if @expose %><% @expose_array.each do |expose_port| %> \
-            --expose=<%= expose_port %><% end %> \
-        <% end %> \
-        <% if @volumes %><% @volumes_array.each do |volume| %> \
-            -v <%= volume %><% end %> \
-        <% end %> \
-        <% if @volumes_from %><% @volumes_from_array.each do |container| %> \
-            --volumes-from <%= container %><% end %> \
-        <% end %> \
-        <% if @net %>--net <%= @net %><% end %> \
-        <% if @lxc_conf_array %><% @lxc_conf_array.each do |lxcconf| %> \
-            --lxc-conf="<%=lxcconf%>"<% end %> \
-        <% end %> \
-        -m <%= @memory_limit %> \
-        <% if not @cpuset_array.empty? %>--cpuset=<%= @cpuset_array.join(',') %><% end %> \
-        <% if @links %><%= @links_array.map {|link| \
-            "--link #{link}" }.join(' ') %> \
-        <% end %> \
-        <% if @use_name %>--name <%= @name %><% end %> \
-        <% if @extra_parameters %><% @extra_parameters_array.each do |param| %>  \
-            <%= param %> <% end %> \
-        <% end -%> \
-        <%= @image %> \
-       <% if @command %> <%= @command %><% end %>
+    $docker rm <%= @sanitised_title %> >/dev/null 2>&1
+    <% if @pull_on_start -%>
+        $docker pull <%= @image %>
+    <% end -%>
+    $docker run \
+    <%= @docker_run_flags %> \
+    --name <%= @sanitised_title %> \
+    <%= @image %> \
+    <% if @command %> <%= @command %><% end %>
+
     retval=$?
     echo
     if [ $retval -eq 0 ]; then
-        touch $lockfile
         success
     else
         failure
@@ -102,22 +84,26 @@ start() {
 }
 
 stop() {
+    echo -n "Stopping $prog: "
+    <% if @before_stop -%>
+        <%= @before_stop %>
+    <% end -%>
+    $docker stop <%= @sanitised_title %>
+    $docker rm <%= @sanitised_title %>
+    return $?
+}
+
+clean() {
     if ! [ -f $cidfile ]; then
         failure
         echo
         printf "$cidfile does not exist.\n"
-        exit 7
     else
         cid="$(cat $cidfile)"
-        if [ -n $cid ]; then
-            echo -n $"Stopping $prog: "
-            $docker stop $(cat $cidfile)
-            retval=$?
-            [ $retval -eq 0 ] && rm -f $lockfile $cidfile
-            return $retval
-        else
-            rm $cidfile
-        fi
+	rm $cidfile
+        $docker rm -f $cid
+        retval=$?
+        return $retval
     fi
 }
 
@@ -129,21 +115,31 @@ case "$1" in
     stop
     ;;
     status)
-    if [ "false" = "$(docker inspect --format='{{.State.Running}}' $(cat $cidfile))"  ] ; then
+    if [ "true" = "$($docker inspect --format='{{.State.Running}}' <%= @sanitised_title %>)" ]; then
+        echo $prog is running
+        exit 0
+    else
         echo $prog not running
         exit 1
     fi
-    docker inspect $(cat $cidfile)
     ;;
     restart|reload)
     stop
+    start
+    ;;
+    clean)
+    clean
+    ;;
+    cleanRestart)
+    stop
+    clean
     start
     ;;
     condrestart)
     [ -f /var/lock/subsys/$prog ] && restart || :
     ;;
     *)
-    echo "Usage: $0 [start|stop|status|reload|restart|probe]"
+    echo "Usage: $0 [start|stop|status|reload|restart|probe|clean|cleanRestart]"
     exit 1
     ;;
 esac
